export const theme01 = {
  body: "#3B4664",
  back_header: "#181F32",
  back_body: "#252D44",
  back_input: "#181F32",
  text_color_primary: "#F3F5F7",
  text_color_secundary: "#474B5E",
  text_color_third: "#F3F5F7",
  btn_background_primary: "#EAE3DB",
  btn_background_secondary: "#647299",
  btn_background_third: "#D13F30",
  btn_hover_background_primary: "#FFFFFC",
  btn_hover_background_secondary: "#A1B2DF",
  btn_hover_background_third: "#F66B5A",
  btn_shadow_color_primary: "#B5A499",
  btn_shadow_color_secundary: "#545F80",
  btn_shadow_color_third: "#8D2013",
};

export const theme02 = {
  body: "#E6E6E6",
  back_header: "#EEEEEE",
  back_body: "#D3CDCD",
  back_input: "#EEEEEE",
  text_color_primary: "#36362C",
  text_color_secundary: "#474B5E",
  text_color_third: "#FCFFFF",
  btn_background_primary: "#E5E4E0",
  btn_background_secondary: "#367D82",
  btn_background_third: "#D13F30",
  btn_hover_background_primary: "#FFFFFF",
  btn_hover_background_secondary: "#62B5BD",
  btn_hover_background_third: "#FF8A38",
  btn_shadow_color_primary: "#A39A8C",
  btn_shadow_color_secundary: "#1B5F66",
  btn_shadow_color_third: "#893A00",
};

export const theme03 = {
  body: "#17062A",
  back_header: "#1E0836",
  back_body: "#1E0836",
  back_input: "#1E0836",
  text_color_primary: "#E1CC66",
  text_color_secundary: "#E1CC66",
  text_color_third: "#FCFFFF",
  btn_background_primary: "#331B4D",
  btn_background_secondary: "#56077C",
  btn_background_third: "#00DECF",
  btn_hover_background_primary: "#6B34AC",
  btn_hover_background_secondary: "#8631B0",
  btn_hover_background_third: "#8631B0",
  btn_shadow_color_primary: "#76228E",
  btn_shadow_color_secundary: "#BA19ED",
  btn_shadow_color_third: "#6BF9F0",
};
